# Generated by Django 6.1 on 2026-08-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fuelprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelPrice',
        ),
    ]
