# Generated by Django 6.1 on 2026-08-16 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_fuelprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_prices_set', to='myapp.station')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
