# Generated by Django 6.1 on 2026-08-17 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_litrewallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fuelRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litres_redeemed', models.DecimalField(decimal_places=3, max_digits=10)),
                ('qr_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('REDEEMED', 'redeemed'), ('EXPIRED', 'expired'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendant_redemption', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_redemption', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LitreLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litres_purchased', models.DecimalField(decimal_places=3, max_digits=10)),
                ('litres_remaining', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('EXHAUSTED', 'exhausted'), ('EXPIRED', 'expired')], default='ACTIVE', max_length=20)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='litre_lot', to='myapp.litrepurchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litre_lot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
