# Generated by Django 6.1 on 2026-08-24 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_fuelredemption_litrelot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='litrelot',
            options={'ordering': ['expires_at']},
        ),
        migrations.AlterModelOptions(
            name='litrepurchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='litrelot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litre_lots', to=settings.AUTH_USER_MODEL),
        ),
    ]
