# Generated by Django 6.1 on 2026-08-26 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_litrelot_options_alter_litrepurchase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitializePaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('litres_to_purchase', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount_to_pay', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('EXPIRED', 'expired'), ('CANCELLED', 'cancelled')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
