# Generated by Django 6.1 on 2026-08-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_initializepaymentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initializepaymentrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('EXPIRED', 'expired'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=10),
        ),
    ]
