# Generated by Django 6.1 on 2026-08-28 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_initializepaymentrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelredemption',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='myapp.station'),
            preserve_default=False,
        ),
    ]
